version: '3'

services:
  zoo-app:
    extends: 
      file: ./zoo-app/docker-compose.yml
      service: zoo-app

  cat-food-app:
    extends: 
      file: ./cat-food-app/docker-compose.yml
      service: cat-food-app

  animal-service:
    container_name: animal-service
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PACT_BROKER_BASE_URL: "http://pact-broker:9292"
    volumes:
      - .:/app
      - animal-service-bundle-cache:/usr/local/bundle

  pact-broker-postgres:
    container_name: pact-broker-postgres
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pact-broker:
    container_name: pact-broker
    image: pactfoundation/pact-broker
    build: .
    ports:
      - "9292:9292"
    depends_on:
      - pact-broker-postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: pact-broker-postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_LOG_LEVEL: DEBUG

volumes:
  animal-service-bundle-cache:
  zoo-app-bundle-cache:
  cat-food-app-bundle-cache:
  postgres-volume:
